### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-integration-testing#104]
It looks like this repository is not compatible with `--incompatible_no_transitive_loads`, see: https://github.com/bazelbuild/bazel-watcher/issues/207

There might be other issues. It may be useful to try other flags, such as `--incompatible_new_actions_api --incompatible_bzl_disallow_load_after_statement --incompatible_no_support_tools_in_action_inputs --incompatible_disallow_filetype --incompatible_merge_genfiles_directory --incompatible_no_transitive_loads --incompatible_disable_deprecated_attr_params --incompatible_disallow_load_labels_to_cross_package_boundaries --incompatible_disallow_dict_plus --incompatible_disallow_old_style_args_add`

**Comment by laurentlb** [comment]
Any update on this?

**Comment by laurentlb** [comment]
cc @ittaiz

**Comment by achew22** [comment]
@laurentlb, I guess I would be willing to fix this but I don't have owners in the repo. Do you have enough admin juice to do that?

**Comment by laurentlb** [comment]
I have no rights on this repo. If you make a pull-request, we'll find someone to merge it.

**Comment by achew22** [comment]
https://github.com/bazelbuild/bazel-integration-testing/pull/107
