### ISSUE TITLE
WorkspaceDriverTest fails with bazel @ HEAD

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel-integration-testing#111]
On Bazel CI `bazel-integration-testing` is failing in the downstream projects because of `WorkspaceDriverTest` (see [logs](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/825#9d29ee14-dcec-49b1-8c4f-1a8c9e4a7efe)).

The test relies on the existence of a file in the runfiles directory (e.g. see [#L37](https://github.com/bazelbuild/bazel-integration-testing/blob/0c72fe23775e730973985bce9d20bc909b32127f/javatests/build/bazel/tests/integration/WorkspaceDriverTest.java#L37)). The file is not embedded into bazel anymore since https://github.com/bazelbuild/bazel/commit/c33ae8af469d615e490fbf503f7fad03e22ea1c6.

**Comment by meteorcloudy** [comment]
@maximn @ittaiz How should we fix this test?

**Comment by ittaiz** [comment]
Do you know by any chance if there is a different file we can rely on
existing?

**Comment by meteorcloudy** [comment]
@iirina @meisterT What's the best way to proceed there?

**Comment by meisterT** [comment]
I think this does rely on internals it probably should not rely on. What you seem want to test is the `copyDirectoryFromRunfiles` method, right? So what about setting up a test where you actually control the runfiles?

**Comment by achew22** [comment]
I kind of did this in https://github.com/bazelbuild/bazel-integration-testing/pull/112, I don't know if that fixes it entirely, but wouldn't mind a 2nd set of eyes.

**Comment by meteorcloudy** [comment]
I temporarily disabled Bazel integration test in Bazel downstream test, please ping us when it's fixed.
You can still view the build status with Bazel@HEAD at https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/99

**Comment by ittaiz** [comment]
@achew22 I think #112 isn't related to the above error of relying on test runner deploy.
Can you PTAL at #113?

**Comment by ittaiz** [comment]
@meteorcloudy can you please enable us again? I'm fairly certain the issue is resolved

**Comment by meteorcloudy** [comment]
@ittaiz Thanks for the fix!

**Comment by meteorcloudy** [comment]
It is green again https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/102
