### ISSUE TITLE
Move APIs from `java.io.File` to `java.nio.file.Path`

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel-integration-testing#44]
`Path` is a newer api which also allows plugging in in memory filesystem for testing and in general is more recommended

**Comment by ittaiz** [comment]
cc @maximn

**Comment by maximn** [comment]
This is a breaking change. Did you mean to do that or just change the internals?

**Comment by ittaiz** [comment]
Yes I did.
Cc @damienmg any strong objections?

**Comment by damienmg** [comment]
No objection Path is definitely better.

**Comment by ittaiz** [comment]
closed by #56
