### ISSUE TITLE
Should we continue to support the JUnit BaseTest API?

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel-integration-testing#46]
@damienmg I'm thinking of dropping support for the BaseTest junit API and just expose the WorkspaceDriver (which of course is totally usable from JUnit).
I feel that composition is much better than inheritance also for this use-case.
WDYT?

**Comment by damienmg** [comment]
Isn't the current API offering the choice between doing the two? I don't have a strong opinion on which one is better, of course not having a base class let people write their test case with a different base test class so I guess this is an argument toward removing the support for it. For the Eclipse Plugin I can do with using the driver directly.

**Comment by ittaiz** [comment]
@damienmg WDYT about keeping the BaseTest only for the setup methods and the driver member? this way it still gives people the comfort but the cost of maintenance (idea by @maximn)

**Comment by damienmg** [comment]
SGTM

**Comment by ittaiz** [comment]
fixed by #49
