### ISSUE TITLE
Share the download cache with the invoking Bazel installation

### ISSUE THREAD

**Issue by hchauvin** [bazelbuild/bazel-integration-testing#63]
... or have another way to share external dependencies.

Currently, the Bazel environment that is created by bazel-integration-testing has a download cache that is separated from the invoking Bazel installation (let's call it the "upstream" download cache).  It is possible to have a download cache when developing by pinning the TEST_TMPDIR, but since the download cache is a content-addressable storage, wouldn't it make sense to simply use the upstream download cache as it would be safe anyway?  In some cases this could greatly improve performance.  Agreed, such external dependencies should be avoided when doing integration testing, but sometimes it is more convenient.

This is not something that could be added right away, though, as it would require Bazel to publish in some way the location of its download cache.

**Comment by ittaiz** [comment]
this is really interesting. @anchlovi is also facing some issues with setting up external dependencies for the `scratch workspace` and your solution sounds really interesting. @anchlovi wdyt?

**Comment by ittaiz** [comment]
Where is `REPOSITORY_CACHE` that you used in the rules_kotlin PR defined?
Also it sounds strange that the `scratch_workspace` will have access to the shared cache directory since its out of its sandbox

**Comment by ittaiz** [comment]
I'll rephrase the last sentence as a question. Were you able to run it with sandboxing?

**Comment by hchauvin** [comment]
Yep, it runs with sandboxing, but because of a horrendous hack involving absolute paths.  Actually in local dev I hardcode this: -"Dbazel.repository.cache=/tmp/cache".  That's clearly not a portable solution :)

I thought of another way of sharing external dependencies, which might actually work across the spectrum, including remote execution, and without touching Bazel: "prewarming".

Here, bazel would be executed during the build phase to generate a download cache, so that the ~14s are only paid once; I actually like that better because you have less assumptions concerning how bazel work, and those assumptions might break when you have, e.g., remote execution.

**Comment by ittaiz** [comment]
I don’t understand what you mean by executing bazel once in the build phase.
Can you elaborate?

**Comment by ittaiz** [comment]
Oh interesting, so you’re thinking of somehow segregating the workspace
creation out so you can also run it as a genrule which will do “bazel
fetch”? But then it doesn’t have network access either

**Comment by hchauvin** [comment]
Ah yes they are not supposed to access the network.  But does it mean that they can't?

Another possibility, in this case, would be to have a new repository rule that uses repository_ctx.download to have a compressed archive.  Then it is possible to use --experimental_distdir (https://github.com/bazelbuild/bazel/blob/beef2c452bb6b1c2dd2b08d3089062f26cccc859/src/main/java/com/google/devtools/build/lib/bazel/repository/RepositoryOptions.java) with a location within the workspace to have all the repository rules cached without rewriting everything.

**Comment by ittaiz** [comment]
I think it can’t. @damienmg do you know?

Re experimental distdir- if you download to within the repo the. Wouldn’t
that mess up your git?
Sorry if I sound like a party pooper

**Comment by hchauvin** [comment]
@damienmg Thank you for the feedback, I agree with you, I don't think that Bazel should expose that, that is in the realm of the test infrastructure.

For the blocking of the network, the "block-network" tag can be added. 

@ittaiz I came up with another approach which feels way less hackish, but it works only for testing bazel > 0.12.0, using --experimental_distdir, see #71.

**Comment by ittaiz** [comment]
Sounds interesting!
I’ll take a look as soon as I can

**Comment by ittaiz** [comment]
fixed by #71 thanks @hchauvin!
