### ISSUE TITLE
WorkpaceDriver API: uniformize getter names

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel-integration-testing#69]
Mosts getters of the WorskpaceDriver are written in the fluent form (e.g. [bazelVersion](
https://github.com/bazelbuild/bazel-integration-testing/blob/master/java/build/bazel/tests/integration/WorkspaceDriver.java#L92)) while [getRunfiles](https://github.com/bazelbuild/bazel-integration-testing/blob/master/java/build/bazel/tests/integration/WorkspaceDriver.java#L59) use the getter form.

Maybe rename `getRunfiles` to `runfiles`?

/cc @ittaiz @natansil

**Comment by ittaiz** [comment]
SGTM

**Comment by natansil** [comment]
👍
